import type {
  Categoria,
  ChatMessage,
  Deporte,
  Federacion,
  PartidoDirecto,
  VideoGuardado,
} from "./types";

export const mockDeportes: Deporte[] = [
  { id: "dep-futbol", nombre: "Fútbol", icono: "⚽" },
  { id: "dep-baloncesto", nombre: "Baloncesto", icono: "🏀" },
  { id: "dep-balonmano", nombre: "Balonmano", icono: "🤾" },
  { id: "dep-futsal", nombre: "Fútbol sala", icono: "🥅" },
];

export const mockCategorias: Categoria[] = [
  { id: "cat-tercera-fed", nombre: "3ª Federación" },
  { id: "cat-segunda-futsal", nombre: "2ª División Nacional FS" },
  { id: "cat-segunda-b-futsal", nombre: "2ª Nacional B FS" },
  { id: "cat-femenino", nombre: "Femenino" },
];

export const mockFederaciones: Federacion[] = [
  { id: "fed-rfef", nombre: "RFEF" },
  { id: "fed-feb", nombre: "FEB" },
  { id: "fed-rfebm", nombre: "RFEBM" },
  { id: "fed-lnfs", nombre: "LNFS" },
];

export const mockPartidoLive: PartidoDirecto = {
  id: "match-live-1",
  home: {
    id: "team-mov",
    nombre: "Movida FC",
    abreviatura: "MOV",
  },
  away: {
    id: "team-ath",
    nombre: "Atleti Costa",
    abreviatura: "ATC",
  },
  competition: "Primera Federación",
  grupo: "Grupo 2",
  jornada: 24,
  status: "LIVE",
  fechaISO: "2026-03-11T18:30:00+01:00",
  clock: "67:12",
  scoreHome: 2,
  scoreAway: 1,
  coverUrl: "/assets/figma/directo-hero.png",
  streamUrl: "#",
  deporte: "dep-futbol",
  categoria: "cat-tercera-fed",
  federacion: "fed-rfef",
  genero: "masculino",
  publicado: true,
};

export const mockOtrosPartidosLive: PartidoDirecto[] = [
  {
    id: "match-live-2",
    home: { id: "team-lev", nombre: "Levante B", abreviatura: "LEV" },
    away: { id: "team-cad", nombre: "Cádiz B", abreviatura: "CAD" },
    competition: "Primera Federación",
    grupo: "Grupo 2",
    jornada: 24,
    status: "LIVE",
    fechaISO: "2026-03-11T18:30:00+01:00",
    clock: "71:08",
    scoreHome: 0,
    scoreAway: 0,
    coverUrl: "/assets/figma/home-directo-1.png",
    deporte: "dep-futbol",
    categoria: "cat-tercera-fed",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
  },
  {
    id: "match-live-3",
    home: { id: "team-est", nombre: "Estudiantes", abreviatura: "EST" },
    away: { id: "team-uni", nombre: "Unicaja", abreviatura: "UNI" },
    competition: "Liga Endesa",
    grupo: "Temporada regular",
    jornada: 24,
    status: "LIVE",
    fechaISO: "2026-03-11T19:00:00+01:00",
    clock: "34:20",
    scoreHome: 76,
    scoreAway: 79,
    coverUrl: "/assets/figma/home-directo-2.png",
    deporte: "dep-baloncesto",
    categoria: "cat-segunda-futsal",
    federacion: "fed-feb",
    genero: "masculino",
    publicado: true,
  },
  {
    id: "match-live-4",
    home: { id: "team-cbm", nombre: "BM Málaga", abreviatura: "MLG" },
    away: { id: "team-bhv", nombre: "Benidorm", abreviatura: "BEN" },
    competition: "Liga ASOBAL",
    grupo: "Temporada regular",
    jornada: 21,
    status: "LIVE",
    fechaISO: "2026-03-11T20:00:00+01:00",
    clock: "48:03",
    scoreHome: 28,
    scoreAway: 26,
    coverUrl: "/assets/figma/home-directo-3.png",
    deporte: "dep-balonmano",
    categoria: "cat-segunda-futsal",
    federacion: "fed-rfebm",
    genero: "masculino",
    publicado: true,
  },
];

const youtubeThumb = (videoId: string) =>
  `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;

const youtubeUrl = (videoId: string) =>
  `https://www.youtube.com/watch?v=${videoId}`;

export const mockVideos: VideoGuardado[] = [
  {
    id: "video-fut-1",
    title: "GRAMA - VILANOVA",
    subtitle: "3ª Federación | Grupo V | Jornada 19",
    dateLabel: "Mar 2026",
    durationLabel: "104 min",
    scoreLabel: "3ª FED",
    thumbUrl: youtubeThumb("lyH_aR01zEU"),
    deporte: "dep-futbol",
    categoria: "cat-tercera-fed",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("lyH_aR01zEU"),
  },
  {
    id: "video-fut-2",
    title: "BADALONA - VILASSAR",
    subtitle: "3ª Federación | Grupo V | Jornada 25",
    dateLabel: "Mar 2026",
    durationLabel: "108 min",
    scoreLabel: "3ª FED",
    thumbUrl: youtubeThumb("TLVWJmq8lvc"),
    deporte: "dep-futbol",
    categoria: "cat-tercera-fed",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("TLVWJmq8lvc"),
  },
  {
    id: "video-fut-3",
    title: "VILASSAR - PERALADA",
    subtitle: "3ª Federación | Grupo V | Jornada 22",
    dateLabel: "Feb 2026",
    durationLabel: "101 min",
    scoreLabel: "3ª FED",
    thumbUrl: youtubeThumb("lQGa2TVUUFY"),
    deporte: "dep-futbol",
    categoria: "cat-tercera-fed",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("lQGa2TVUUFY"),
  },
  {
    id: "video-fut-4",
    title: "FE GRAMA - CF CAN VIDALET",
    subtitle: "3ª Federación | Grupo 5 | Jornada 22",
    dateLabel: "Feb 2026",
    durationLabel: "97 min",
    scoreLabel: "3ª FED",
    thumbUrl: youtubeThumb("44THyyvvdOA"),
    deporte: "dep-futbol",
    categoria: "cat-tercera-fed",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("44THyyvvdOA"),
  },
  {
    id: "video-fut-5",
    title: "CE EUROPA B - LLEIDA CF",
    subtitle: "3ª Federación | Jornada 21",
    dateLabel: "Feb 2026",
    durationLabel: "99 min",
    scoreLabel: "3ª FED",
    thumbUrl: youtubeThumb("TW-Egxju8zo"),
    deporte: "dep-futbol",
    categoria: "cat-tercera-fed",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("TW-Egxju8zo"),
  },
  {
    id: "video-fs-1",
    title: "SANT QUIRZE - NUNCYS EL PILAR",
    subtitle: "2ª División Nacional Futsal | Jornada 25",
    dateLabel: "Mar 2026",
    durationLabel: "92 min",
    scoreLabel: "2ª FS",
    thumbUrl: youtubeThumb("teuD8D9rPA4"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("teuD8D9rPA4"),
  },
  {
    id: "video-fs-2",
    title: "BARÇA ATLÈTIC - INAGROUP EL EJIDO",
    subtitle: "2ª División Nacional Futsal | Jornada 23",
    dateLabel: "Mar 2026",
    durationLabel: "95 min",
    scoreLabel: "2ª FS",
    thumbUrl: youtubeThumb("MZ3ORwfu_2A"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("MZ3ORwfu_2A"),
  },
  {
    id: "video-fs-3",
    title: "BARÇA ATLÈTIC - CD MELISTAR FS",
    subtitle: "2ª División Nacional Futsal | Jornada 19",
    dateLabel: "Feb 2026",
    durationLabel: "94 min",
    scoreLabel: "2ª FS",
    thumbUrl: youtubeThumb("r8i8E4wGyg8"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("r8i8E4wGyg8"),
  },
  {
    id: "video-fs-4",
    title: "BARÇA ATLÈTIC - CD LEGANÉS FS",
    subtitle: "2ª División Nacional Futsal | Jornada 21",
    dateLabel: "Feb 2026",
    durationLabel: "96 min",
    scoreLabel: "2ª FS",
    thumbUrl: youtubeThumb("DpQfgVXe1Dk"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("DpQfgVXe1Dk"),
  },
  {
    id: "video-fs-5",
    title: "CN SABADELL - ILLES BALEARS PALMA FUTSAL",
    subtitle: "2ª División Nacional Futsal | Grupo 3 | Jornada 21",
    dateLabel: "Feb 2026",
    durationLabel: "91 min",
    scoreLabel: "2ª FS",
    thumbUrl: youtubeThumb("eTJf01xtUxA"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("eTJf01xtUxA"),
  },
  {
    id: "video-fsb-1",
    title: "SANT QUIRZE - CCR BAIX SUD",
    subtitle: "2ª Nacional B Futsal | Grupo 3 | Jornada 23",
    dateLabel: "Mar 2026",
    durationLabel: "93 min",
    scoreLabel: "2ª B",
    thumbUrl: youtubeThumb("EBCWt3gIhhw"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-b-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("EBCWt3gIhhw"),
  },
  {
    id: "video-fsb-2",
    title: "SANT QUIRZE - MATARÓ",
    subtitle: "2ª División B Futsal | Grupo 3 | Jornada 21",
    dateLabel: "Feb 2026",
    durationLabel: "90 min",
    scoreLabel: "2ª B",
    thumbUrl: youtubeThumb("rRtLgZw1Sz4"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-b-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("rRtLgZw1Sz4"),
  },
  {
    id: "video-fsb-3",
    title: "INDUSTRIAS SANTA COLOMA B - CEREZO FUTSAL LLEIDA",
    subtitle: "2ª División Nacional B Fútbol Sala",
    dateLabel: "Feb 2026",
    durationLabel: "92 min",
    scoreLabel: "2ª B",
    thumbUrl: youtubeThumb("4w66g-kNA3o"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-b-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("4w66g-kNA3o"),
  },
  {
    id: "video-fsb-4",
    title: "SANT QUIRZE - FUTSAL IBI",
    subtitle: "2ª División Nacional B Fútbol Sala | Grupo 3 | Jornada 18",
    dateLabel: "Feb 2026",
    durationLabel: "94 min",
    scoreLabel: "2ª B",
    thumbUrl: youtubeThumb("Z9c5nJhlgp0"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-b-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("Z9c5nJhlgp0"),
  },
  {
    id: "video-fsb-5",
    title: "SANT QUIRZE FS - BISONTES CASTELLÓN",
    subtitle: "2ª División Nacional B Futsal | Grupo 3 | Jornada 15",
    dateLabel: "Ene 2026",
    durationLabel: "91 min",
    scoreLabel: "2ª B",
    thumbUrl: youtubeThumb("ui4fRLB7Fzk"),
    deporte: "dep-futsal",
    categoria: "cat-segunda-b-futsal",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: youtubeUrl("ui4fRLB7Fzk"),
  },
  {
    id: "video-fem-1",
    title: "Playoff femenino | Semifinal ida",
    subtitle: "Partido completo y mejores acciones",
    dateLabel: "Mar 2026",
    durationLabel: "96 min",
    scoreLabel: "FEM",
    thumbUrl: "/assets/figma/home-directo-1.png",
    deporte: "dep-futbol",
    categoria: "cat-femenino",
    federacion: "fed-rfef",
    genero: "femenino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-fem-2",
    title: "Derbi femenino | Jornada 12",
    subtitle: "Choque completo con final ajustado",
    dateLabel: "Feb 2026",
    durationLabel: "94 min",
    scoreLabel: "FEM",
    thumbUrl: "/assets/figma/home-directo-2.png",
    deporte: "dep-futbol",
    categoria: "cat-femenino",
    federacion: "fed-rfef",
    genero: "femenino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-fem-3",
    title: "Copa femenina | Cuartos de final",
    subtitle: "Encuentro íntegro desde el pitido inicial",
    dateLabel: "Feb 2026",
    durationLabel: "98 min",
    scoreLabel: "FEM",
    thumbUrl: "/assets/figma/home-directo-3.png",
    deporte: "dep-futbol",
    categoria: "cat-femenino",
    federacion: "fed-rfef",
    genero: "femenino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-fem-4",
    title: "Fútbol sala femenino | Jornada 8",
    subtitle: "Partido completo con resumen final",
    dateLabel: "Ene 2026",
    durationLabel: "88 min",
    scoreLabel: "FEM",
    thumbUrl: "/assets/figma/dashboard-live.png",
    deporte: "dep-futsal",
    categoria: "cat-femenino",
    federacion: "fed-lnfs",
    genero: "femenino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-fem-5",
    title: "Final femenina | Copa autonómica",
    subtitle: "Retransmisión completa",
    dateLabel: "Ene 2026",
    durationLabel: "90 min",
    scoreLabel: "FEM",
    thumbUrl: "/assets/figma/videos-thumb-1.png",
    deporte: "dep-futsal",
    categoria: "cat-femenino",
    federacion: "fed-lnfs",
    genero: "femenino",
    publicado: true,
    vodUrl: "#",
  },
];

export const mockMensajes: ChatMessage[] = [
  {
    id: "msg-1",
    emoji: "🔥",
    name: "Lucía",
    timeLabel: "18:41",
    message: "Qué golazo, menuda asistencia al espacio.",
    userRole: "user",
  },
  {
    id: "msg-2",
    emoji: "👏",
    name: "Carlos",
    timeLabel: "18:42",
    message: "El portero estaba vendidísimo.",
    userRole: "suscriptor",
  },
  {
    id: "msg-3",
    emoji: "⚽",
    name: "Marta",
    timeLabel: "18:43",
    message: "A ver si aguantan estos minutos finales.",
    userRole: "user",
  },
  {
    id: "msg-4",
    emoji: "🎥",
    name: "Movida TV",
    timeLabel: "18:44",
    message: "Recordad que el resumen estará disponible al terminar.",
    userRole: "admin",
  },
];
