import type {
  Categoria,
  ChatMessage,
  Deporte,
  Federacion,
  PartidoDirecto,
  VideoGuardado,
} from "./types";

export const mockDeportes: Deporte[] = [
  { id: "dep-futbol", nombre: "Fútbol", icono: "⚽" },
  { id: "dep-baloncesto", nombre: "Baloncesto", icono: "🏀" },
  { id: "dep-balonmano", nombre: "Balonmano", icono: "🤾" },
  { id: "dep-futsal", nombre: "Fútbol sala", icono: "🥅" },
];

export const mockCategorias: Categoria[] = [
  { id: "cat-masculino", nombre: "Masculino" },
  { id: "cat-femenino", nombre: "Femenino" },
  { id: "cat-base", nombre: "Base" },
  { id: "cat-profesional", nombre: "Profesional" },
];

export const mockFederaciones: Federacion[] = [
  { id: "fed-rfef", nombre: "RFEF" },
  { id: "fed-feb", nombre: "FEB" },
  { id: "fed-rfebm", nombre: "RFEBM" },
  { id: "fed-lnfs", nombre: "LNFS" },
];

export const mockPartidoLive: PartidoDirecto = {
  id: "match-live-1",
  home: {
    id: "team-mov",
    nombre: "Movida FC",
    abreviatura: "MOV",
  },
  away: {
    id: "team-ath",
    nombre: "Atleti Costa",
    abreviatura: "ATC",
  },
  competition: "Primera Federación",
  grupo: "Grupo 2",
  jornada: 24,
  status: "LIVE",
  fechaISO: "2026-03-11T18:30:00+01:00",
  clock: "67:12",
  scoreHome: 2,
  scoreAway: 1,
  coverUrl: "/assets/figma/directo-hero.png",
  streamUrl: "#",
  deporte: "dep-futbol",
  categoria: "cat-profesional",
  federacion: "fed-rfef",
  genero: "masculino",
  publicado: true,
};

export const mockOtrosPartidosLive: PartidoDirecto[] = [
  {
    id: "match-live-2",
    home: { id: "team-lev", nombre: "Levante B", abreviatura: "LEV" },
    away: { id: "team-cad", nombre: "Cádiz B", abreviatura: "CAD" },
    competition: "Primera Federación",
    grupo: "Grupo 2",
    jornada: 24,
    status: "LIVE",
    fechaISO: "2026-03-11T18:30:00+01:00",
    clock: "71:08",
    scoreHome: 0,
    scoreAway: 0,
    coverUrl: "/assets/figma/home-directo-1.png",
    deporte: "dep-futbol",
    categoria: "cat-profesional",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
  },
  {
    id: "match-live-3",
    home: { id: "team-est", nombre: "Estudiantes", abreviatura: "EST" },
    away: { id: "team-uni", nombre: "Unicaja", abreviatura: "UNI" },
    competition: "Liga Endesa",
    grupo: "Temporada regular",
    jornada: 24,
    status: "LIVE",
    fechaISO: "2026-03-11T19:00:00+01:00",
    clock: "34:20",
    scoreHome: 76,
    scoreAway: 79,
    coverUrl: "/assets/figma/home-directo-2.png",
    deporte: "dep-baloncesto",
    categoria: "cat-profesional",
    federacion: "fed-feb",
    genero: "masculino",
    publicado: true,
  },
  {
    id: "match-live-4",
    home: { id: "team-cbm", nombre: "BM Málaga", abreviatura: "MLG" },
    away: { id: "team-bhv", nombre: "Benidorm", abreviatura: "BEN" },
    competition: "Liga ASOBAL",
    grupo: "Temporada regular",
    jornada: 21,
    status: "LIVE",
    fechaISO: "2026-03-11T20:00:00+01:00",
    clock: "48:03",
    scoreHome: 28,
    scoreAway: 26,
    coverUrl: "/assets/figma/home-directo-3.png",
    deporte: "dep-balonmano",
    categoria: "cat-profesional",
    federacion: "fed-rfebm",
    genero: "masculino",
    publicado: true,
  },
];

export const mockVideos: VideoGuardado[] = [
  {
    id: "video-1",
    title: "Movida FC vs Atleti Costa",
    subtitle: "Resumen completo y mejores jugadas",
    dateLabel: "11 Mar 2026",
    durationLabel: "12 min",
    scoreLabel: "2 - 1",
    thumbUrl: "/assets/figma/videos-thumb-1.png",
    deporte: "dep-futbol",
    categoria: "cat-profesional",
    federacion: "fed-rfef",
    genero: "masculino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-2",
    title: "Estudiantes vs Unicaja",
    subtitle: "Último cuarto íntegro",
    dateLabel: "10 Mar 2026",
    durationLabel: "18 min",
    scoreLabel: "76 - 79",
    thumbUrl: "/assets/figma/videos-thumb-2.png",
    deporte: "dep-baloncesto",
    categoria: "cat-profesional",
    federacion: "fed-feb",
    genero: "masculino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-3",
    title: "BM Málaga vs Benidorm",
    subtitle: "Final ajustado con remontada",
    dateLabel: "09 Mar 2026",
    durationLabel: "9 min",
    scoreLabel: "28 - 26",
    thumbUrl: "/assets/figma/directo-hero.png",
    deporte: "dep-balonmano",
    categoria: "cat-profesional",
    federacion: "fed-rfebm",
    genero: "masculino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-4",
    title: "Playoff femenino",
    subtitle: "Semifinal ida",
    dateLabel: "08 Mar 2026",
    durationLabel: "14 min",
    scoreLabel: "1 - 0",
    thumbUrl: "/assets/figma/home-directo-1.png",
    deporte: "dep-futbol",
    categoria: "cat-femenino",
    federacion: "fed-rfef",
    genero: "femenino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-5",
    title: "Derbi de cantera",
    subtitle: "Lo mejor de la jornada base",
    dateLabel: "07 Mar 2026",
    durationLabel: "11 min",
    scoreLabel: "3 - 3",
    thumbUrl: "/assets/figma/home-directo-2.png",
    deporte: "dep-futbol",
    categoria: "cat-base",
    federacion: "fed-rfef",
    genero: "mixto",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-6",
    title: "Top 10 asistencias",
    subtitle: "Selección semanal",
    dateLabel: "06 Mar 2026",
    durationLabel: "7 min",
    scoreLabel: "TOP 10",
    thumbUrl: "/assets/figma/home-directo-3.png",
    deporte: "dep-baloncesto",
    categoria: "cat-profesional",
    federacion: "fed-feb",
    genero: "masculino",
    publicado: true,
    vodUrl: "#",
  },
  {
    id: "video-7",
    title: "Clásico de fútbol sala",
    subtitle: "Partido completo",
    dateLabel: "05 Mar 2026",
    durationLabel: "42 min",
    scoreLabel: "5 - 4",
    thumbUrl: "/assets/figma/dashboard-live.png",
    deporte: "dep-futsal",
    categoria: "cat-profesional",
    federacion: "fed-lnfs",
    genero: "masculino",
    publicado: true,
    vodUrl: "#",
  },
];

export const mockMensajes: ChatMessage[] = [
  {
    id: "msg-1",
    emoji: "🔥",
    name: "Lucía",
    timeLabel: "18:41",
    message: "Qué golazo, menuda asistencia al espacio.",
    userRole: "user",
  },
  {
    id: "msg-2",
    emoji: "👏",
    name: "Carlos",
    timeLabel: "18:42",
    message: "El portero estaba vendidísimo.",
    userRole: "suscriptor",
  },
  {
    id: "msg-3",
    emoji: "⚽",
    name: "Marta",
    timeLabel: "18:43",
    message: "A ver si aguantan estos minutos finales.",
    userRole: "user",
  },
  {
    id: "msg-4",
    emoji: "🎥",
    name: "Movida TV",
    timeLabel: "18:44",
    message: "Recordad que el resumen estará disponible al terminar.",
    userRole: "admin",
  },
];
