-- PostgreSQL schema generated from the provided ER diagram.
-- Assumptions taken from the image:
-- 1. All foreign keys in the diagram are required (NOT NULL).
-- 2. "Datetime" maps to TIMESTAMP WITHOUT TIME ZONE.
-- 3. Integer primary keys are auto-generated identities.

BEGIN;

CREATE TABLE roles (
  admin INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol VARCHAR(20) NOT NULL
);

CREATE TABLE tipos (
  id_tipo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL
);

CREATE TABLE estados (
  id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado VARCHAR(30) NOT NULL
);

CREATE TABLE generos (
  id_genero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL
);

CREATE TABLE deportes (
  id_deporte INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_deporte VARCHAR(50) NOT NULL,
  descripcion VARCHAR(234)
);

CREATE TABLE directos (
  id_directo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url_streaming VARCHAR(40) NOT NULL,
  estado VARCHAR(20) NOT NULL
);

CREATE TABLE usuarios (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL,
  email VARCHAR(35) NOT NULL,
  password VARCHAR(50) NOT NULL,
  fecha_registro DATE NOT NULL,
  admin INTEGER NOT NULL,
  CONSTRAINT fk_roles_usuarios
    FOREIGN KEY (admin)
    REFERENCES roles (admin)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX ix_usuarios_admin ON usuarios (admin);

CREATE TABLE federaciones (
  id_federacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_federacion VARCHAR(20) NOT NULL,
  genero_federacion VARCHAR(20) NOT NULL,
  id_deporte INTEGER NOT NULL,
  CONSTRAINT fk_deporte_federaciones
    FOREIGN KEY (id_deporte)
    REFERENCES deportes (id_deporte)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX ix_federaciones_id_deporte ON federaciones (id_deporte);

CREATE TABLE equipos (
  id_equipo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_equipo VARCHAR(30) NOT NULL,
  id_deporte INTEGER NOT NULL,
  id_federacion INTEGER NOT NULL,
  id_genero INTEGER NOT NULL,
  CONSTRAINT fk_deportes_equipos
    FOREIGN KEY (id_deporte)
    REFERENCES deportes (id_deporte)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_federaciones_equipos
    FOREIGN KEY (id_federacion)
    REFERENCES federaciones (id_federacion)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_genero_equipos
    FOREIGN KEY (id_genero)
    REFERENCES generos (id_genero)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX ix_equipos_id_deporte ON equipos (id_deporte);
CREATE INDEX ix_equipos_id_federacion ON equipos (id_federacion);
CREATE INDEX ix_equipos_id_genero ON equipos (id_genero);

CREATE TABLE materiales (
  id_material INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  fecha_fin TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  id_usuario INTEGER NOT NULL,
  id_tipo INTEGER NOT NULL,
  id_estado INTEGER NOT NULL,
  CONSTRAINT fk_usuarios_materiales
    FOREIGN KEY (id_usuario)
    REFERENCES usuarios (id_usuario)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_tipos_materiales
    FOREIGN KEY (id_tipo)
    REFERENCES tipos (id_tipo)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_estados_materiales
    FOREIGN KEY (id_estado)
    REFERENCES estados (id_estado)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX ix_materiales_id_usuario ON materiales (id_usuario);
CREATE INDEX ix_materiales_id_tipo ON materiales (id_tipo);
CREATE INDEX ix_materiales_id_estado ON materiales (id_estado);

CREATE TABLE comentarios (
  id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_publicacion DATE NOT NULL,
  minuto_video VARCHAR(20) NOT NULL,
  contenido VARCHAR(50) NOT NULL,
  id_directo INTEGER NOT NULL,
  id_usuario INTEGER NOT NULL,
  CONSTRAINT fk_directos_comentarios
    FOREIGN KEY (id_directo)
    REFERENCES directos (id_directo)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_usuarios_comentarios
    FOREIGN KEY (id_usuario)
    REFERENCES usuarios (id_usuario)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX ix_comentarios_id_directo ON comentarios (id_directo);
CREATE INDEX ix_comentarios_id_usuario ON comentarios (id_usuario);

COMMIT;
